# E-commerce Sales Analysis

This notebook analyzes an e-commerce sales dataset using **Python and Pandas**.

### Objectives
- Load and inspect the dataset
- Select and filter data
- Sort orders
- Use `groupby()` and aggregation functions
- Analyze sales by category, city, product, and payment method
- Identify top-performing products/categories and specific orders
- Write meaningful observations

## 1. Import Libraries and Load Dataset

In [ ]:
import pandas as pd
import numpy as np

# Load the CSV file
df = pd.read_csv("Day8_Ecommerce_Sales_Dataset.csv")

# Convert Order_Date to datetime
df["Order_Date"] = pd.to_datetime(df["Order_Date"])

df.head()

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

## 2. Basic Dataset Exploration

In [ ]:
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

print("\nDataset information:")
df.info()

print("\nDescriptive statistics:")
display(df.describe(include="all").T)

Shape: (100, 13)

Columns:
['Order_ID', 'Order_Date', 'Customer', 'City', 'Region', 'Category', 'Product', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Rating', 'Payment_Method']

Data types:
Order_ID                     int64
Order_Date          datetime64[ns]
Customer                    object
City                        object
Region                      object
Category                    object
Product                     object
Quantity                     int64
Unit_Price                   int64
Discount_Percent             int64
Total_Sales                float64
Rating                     float64
Payment_Method              object
dtype: object

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          100 non-null    int64
 1   Order_Date        100 non-null    datetime64[ns]
 2   Customer          100 non-null    object
 3   City              100 non-null    object
 4   Region            100 non-null    object
 5   Category          100 non-null    object
 6   Product           100 non-null    object
 7   Quantity          100 non-null    int64
 8   Unit_Price        100 non-null    int64
 9   Discount_Percent  100 non-null    int64
 10  Total_Sales       100 non-null    float64
 11  Rating            100 non-null    float64
 12  Payment_Method    100 non-null    object
dtypes: datetime64[ns](1), float64(2), int64(4), object(6)
memory usage: 10.3+ KB

Descriptive statistics:

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
Order_ID,100.0,NaN,NaN,NaN,1050.5,1001.0,1025.75,1050.5,1075.25,1100.0,29.011492
Order_Date,100,NaN,NaN,NaN,2026-04-02 03:07:12,2026-01-01 00:00:00,2026-02-23 00:00:00,2026-03-29 00:00:00,2026-05-16 00:00:00,2026-06-30 00:00:00,NaN
Customer,100,25,Aditya Verma,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,100,15,Chennai,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Region,100,4,North,38,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,100,5,Sports,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product,100,23,Wireless Headphones,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,100.0,NaN,NaN,NaN,2.94,1.0,2.0,3.0,4.0,5.0,1.391315
Unit_Price,100.0,NaN,NaN,NaN,1647.0,499.0,799.0,1499.0,2499.0,3499.0,970.054669
Discount_Percent,100.0,NaN,NaN,NaN,6.5,0.0,0.0,5.0,11.25,15.0,6.092718
Total_Sales,100.0,NaN,NaN,NaN,4472.6295,449.1,1948.05,3228.3,6427.5625,13995.0,3324.306691
Rating,100.0,NaN,NaN,NaN,4.322,3.5,4.1,4.3,4.7,5.0,0.414285
Payment_Method,100,5,UPI,26,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 3. Data Selection

In [ ]:
# Select a single column
display(df["Product"].head())

# Select multiple columns
display(df[["Order_ID", "City", "Category", "Product", "Quantity", "Total_Sales"]].head())

# Select rows with iloc
display(df.iloc[0:5, 0:6])

# Select rows with loc
display(
    df.loc[df["Total_Sales"] > 10000,
           ["Order_ID", "Product", "Total_Sales"]].head(10)
)

0    Wireless Headphones
1          Running Shoes
2             Power Bank
3    Mechanical Keyboard
4            Smart Watch
Name: Product, dtype: object

,Order_ID,City,Category,Product,Quantity,Total_Sales
0,1001,Hyderabad,Electronics,Wireless Headphones,3,4497.00
1,1002,Jammu,Sports,Running Shoes,1,2799.00
2,1003,Chennai,Electronics,Power Bank,2,2038.30
3,1004,Lucknow,Electronics,Mechanical Keyboard,4,9496.20
4,1005,Jammu,Electronics,Smart Watch,1,3134.05

   Order_ID Order_Date      Customer       City Region     Category
0      1001 2026-02-27     Kabir Ali  Hyderabad  South  Electronics
1      1002 2026-01-24  Aditya Verma      Jammu  North       Sports
2      1003 2026-04-18    Sara Ahmed    Chennai  South  Electronics
3      1004 2026-03-13     Kabir Ali    Lucknow  North  Electronics
4      1005 2026-03-30   Priya Menon      Jammu  North  Electronics

    Order_ID        Product  Total_Sales
12      1013         Jacket     10620.75
47      1048   Coffee Maker     10497.00
48      1049  Running Shoes     13995.00
52      1053  Running Shoes     13295.25
84      1085   Coffee Maker     12596.40
89      1090    Cricket Bat     12495.00

## 4. Filtering

In [ ]:
# Orders with sales greater than ₹5,000
sales_above_5000 = df[df["Total_Sales"] > 5000]
display(sales_above_5000[["Order_ID", "Product", "Total_Sales"]].head(10))

# Orders where quantity is at least 4
quantity_at_least_4 = df[df["Quantity"] >= 4]
display(quantity_at_least_4[["Order_ID", "Product", "Quantity", "Total_Sales"]].head(10))

# Sports category orders
sports_orders = df[df["Category"] == "Sports"]
display(sports_orders[["Order_ID", "Product", "Quantity", "Total_Sales"]].head(10))

# UPI orders
upi_orders = df[df["Payment_Method"] == "UPI"]
display(upi_orders[["Order_ID", "Product", "Total_Sales", "Payment_Method"]].head(10))

# Combined filter
sports_high_value = df[
    (df["Category"] == "Sports") & (df["Total_Sales"] > 5000)
]
display(sports_high_value[["Order_ID", "Product", "Total_Sales"]])

    Order_ID              Product  Total_Sales
3       1004  Mechanical Keyboard      9496.20
7       1008               Hoodie      6076.20
9       1010               Jacket      8996.40
10      1011         Coffee Maker      6998.00
12      1013               Jacket     10620.75
13      1014        Running Shoes      8397.00
16      1017          Cricket Bat      7497.00
18      1019               Jacket      7497.00
27      1028  Wireless Headphones      5696.20
28      1029  Wireless Headphones      5696.20

    Order_ID              Product  Quantity  Total_Sales
3       1004  Mechanical Keyboard         4      9496.20
7       1008               Hoodie         4      6076.20
9       1010               Jacket         4      8996.40
12      1013               Jacket         5     10620.75
15      1016        The Alchemist         4      1696.60
24      1025             Football         5      3995.00
26      1027             Football         5      3395.75
27      1028  Wireless Headphones         4      5696.20
28      1029  Wireless Headphones         4      5696.20
29      1030   Python Programming         4      2996.00

    Order_ID        Product  Quantity  Total_Sales
1       1002  Running Shoes         1      2799.00
11      1012    Cricket Bat         2      4498.20
13      1014  Running Shoes         3      8397.00
16      1017    Cricket Bat         3      7497.00
20      1021       Yoga Mat         1       809.10
22      1023       Football         3      2157.30
23      1024  Running Shoes         1      2799.00
24      1025       Football         5      3995.00
26      1027       Football         5      3395.75
30      1031       Yoga Mat         1       764.15

    Order_ID              Product  Total_Sales Payment_Method
4       1005          Smart Watch      3134.05            UPI
10      1011         Coffee Maker      6998.00            UPI
13      1014        Running Shoes      8397.00            UPI
14      1015  Wireless Headphones      2998.00            UPI
15      1016        The Alchemist      1696.60            UPI
18      1019               Jacket      7497.00            UPI
19      1020        Mixer Grinder      2999.00            UPI
23      1024        Running Shoes      2799.00            UPI
24      1025             Football      3995.00            UPI
27      1028  Wireless Headphones      5696.20            UPI

    Order_ID        Product  Total_Sales
13      1014  Running Shoes      8397.00
16      1017    Cricket Bat      7497.00
37      1038   Dumbbell Set      9495.25
48      1049  Running Shoes     13995.00
52      1053  Running Shoes     13295.25
58      1059    Cricket Bat      8496.60
59      1060   Dumbbell Set      5397.30
89      1090    Cricket Bat     12495.00
92      1093    Cricket Bat      8496.60
95      1096   Dumbbell Set      9495.25

## 5. Sorting

In [ ]:
# Highest-value orders
top_orders = df.sort_values("Total_Sales", ascending=False)
display(
    top_orders[["Order_ID", "City", "Category", "Product", "Total_Sales"]].head(10)
)

# Lowest-value orders
lowest_orders = df.sort_values("Total_Sales")
display(
    lowest_orders[["Order_ID", "City", "Category", "Product", "Total_Sales"]].head(10)
)

# Orders with the highest quantity
top_quantity_orders = df.sort_values("Quantity", ascending=False)
display(
    top_quantity_orders[["Order_ID", "Product", "Quantity", "Total_Sales"]].head(10)
)

    Order_ID        City        Category              Product  Total_Sales
48      1049      Mumbai          Sports        Running Shoes     13995.00
52      1053   Hyderabad          Sports        Running Shoes     13295.25
84      1085   Hyderabad  Home & Kitchen         Coffee Maker     12596.40
89      1090     Lucknow          Sports          Cricket Bat     12495.00
12      1013     Lucknow        Clothing               Jacket     10620.75
47      1048     Lucknow  Home & Kitchen         Coffee Maker     10497.00
69      1070       Delhi        Clothing               Jacket      9996.00
79      1080       Delhi        Clothing               Jacket      9996.00
51      1052  Chandigarh     Electronics  Mechanical Keyboard      9496.20
3       1004     Lucknow     Electronics  Mechanical Keyboard      9496.20

    Order_ID        City  Category                  Product  Total_Sales
5       1006       Kochi     Books            The Alchemist       449.10
62      1063  Chandigarh     Books            The Alchemist       449.10
73      1074     Lucknow     Books            Atomic Habits       539.10
96      1097      Mumbai  Clothing                  T-Shirt       679.15
60      1061   Bengaluru     Books       Python Programming       711.55
82      1083       Jammu    Sports                 Football       759.05
30      1031   Ahmedabad    Sports                 Yoga Mat       764.15
42      1043      Jaipur  Clothing                  T-Shirt       799.00
20      1021  Chandigarh    Sports                 Yoga Mat       809.10
77      1078     Kolkata     Books  Machine Learning Basics       899.10

    Order_ID                Product  Quantity  Total_Sales
26      1027               Football         5      3395.75
24      1025               Football         5      3995.00
12      1013                 Jacket         5     10620.75
37      1038           Dumbbell Set         5      9495.25
71      1072               Yoga Mat         5      4045.50
72      1073          Atomic Habits         5      2545.75
80      1081        Electric Kettle         5      6370.75
83      1084         Wireless Mouse         5      4045.50
95      1096           Dumbbell Set         5      9495.25
99      1100  Data Science Handbook         5      4495.00

## 6. Overall Sales Statistics

In [ ]:
total_sales = df["Total_Sales"].sum()
average_sales = df["Total_Sales"].mean()
highest_sales = df["Total_Sales"].max()
lowest_sales = df["Total_Sales"].min()
total_quantity = df["Quantity"].sum()
number_of_orders = df["Order_ID"].nunique()

overall_stats = pd.Series({
    "Total Sales": total_sales,
    "Average Sales per Order": average_sales,
    "Highest Order Sales": highest_sales,
    "Lowest Order Sales": lowest_sales,
    "Total Quantity Sold": total_quantity,
    "Number of Orders": number_of_orders
})

display(overall_stats.to_frame("Value"))

                               Value
Total Sales              447262.9500
Average Sales per Order    4472.6295
Highest Order Sales       13995.0000
Lowest Order Sales          449.1000
Total Quantity Sold         294.0000
Number of Orders            100.0000

## 7. Sales by Category

In [ ]:
category_summary = (
    df.groupby("Category")
      .agg(
          Total_Sales=("Total_Sales", "sum"),
          Average_Sales=("Total_Sales", "mean"),
          Total_Quantity=("Quantity", "sum"),
          Number_of_Orders=("Order_ID", "count")
      )
      .sort_values("Total_Sales", ascending=False)
)

display(category_summary)

                Total_Sales  Average_Sales  Total_Quantity  Number_of_Orders
Category
Sports            136026.45    5441.058000              79                25
Home & Kitchen    113329.90    5396.661905              59                21
Electronics        92086.00    4846.631579              57                19
Clothing           69028.20    4930.585714              39                14
Books              36792.40    1752.019048              60                21

## 8. Sales by City

In [ ]:
city_summary = (
    df.groupby("City")
      .agg(
          Total_Sales=("Total_Sales", "sum"),
          Total_Quantity=("Quantity", "sum"),
          Number_of_Orders=("Order_ID", "count")
      )
      .sort_values("Total_Sales", ascending=False)
)

display(city_summary)

             Total_Sales  Total_Quantity  Number_of_Orders
City
Hyderabad       59076.45              25                 7
Chennai         47493.20              29                10
Lucknow         46194.65              22                 6
Pune            41908.55              34                10
Mumbai          41457.80              23                 8
Kochi           37257.50              29                 9
Chandigarh      34539.65              22                 8
Delhi           30882.80              18                 6
Jaipur          25534.00              17                 7
Kolkata         20169.00              24                 7
Jammu           16059.75              11                 6
Ahmedabad       14788.70              12                 6
Bengaluru       13524.30              14                 4
Srinagar        11778.60              12                 5
Bhubaneswar      6598.00               2                 1

## 9. Product Performance

In [ ]:
product_summary = (
    df.groupby("Product")
      .agg(
          Total_Sales=("Total_Sales", "sum"),
          Total_Quantity=("Quantity", "sum"),
          Number_of_Orders=("Order_ID", "count")
      )
      .sort_values("Total_Sales", ascending=False)
)

print("Top 10 products by total sales:")
display(product_summary.head(10))

print("Top 10 products by quantity sold:")
display(product_summary.sort_values("Total_Quantity", ascending=False).head(10))

Top 10 products by total sales:

                     Total_Sales  Total_Quantity  Number_of_Orders
Product
Coffee Maker            51610.25              16                 7
Jacket                  47106.15              20                 5
Cricket Bat             41483.40              18                 5
Running Shoes           41285.25              15                 5
Wireless Headphones     33877.40              23                 7
Dumbbell Set            30184.90              16                 5
Mechanical Keyboard     26489.40              11                 3
Electric Kettle         26382.40              19                 5
Mixer Grinder           25341.55               9                 4
Smart Watch             15670.25               5                 3

Top 10 products by quantity sold:

                     Total_Sales  Total_Quantity  Number_of_Orders
Product
Wireless Headphones     33877.40              23                 7
Atomic Habits           11590.65              21                 6
Jacket                  47106.15              20                 5
Electric Kettle         26382.40              19                 5
Cricket Bat             41483.40              18                 5
The Alchemist            7485.00              17                 6
Coffee Maker            51610.25              16                 7
Dumbbell Set            30184.90              16                 5
Yoga Mat                12765.80              16                 6
Water Bottle             9995.70              15                 5

## 10. Payment Method Analysis

In [ ]:
payment_summary = (
    df.groupby("Payment_Method")
      .agg(
          Total_Sales=("Total_Sales", "sum"),
          Average_Sales=("Total_Sales", "mean"),
          Number_of_Orders=("Order_ID", "count")
      )
      .sort_values("Total_Sales", ascending=False)
)

display(payment_summary)

                  Total_Sales  Average_Sales  Number_of_Orders
Payment_Method
Credit Card         106540.25    4842.738636                22
Debit Card           98064.90    4903.245000                20
Net Banking          96371.25    5668.897059                17
UPI                  96163.25    3698.586538                26
Cash on Delivery     50123.30    3341.553333                15

## 11. Identifying Specific Orders

In [ ]:
# Highest-sales order
highest_order = df.loc[df["Total_Sales"].idxmax()]
print("Highest-sales order:")
display(highest_order.to_frame("Value"))

# Lowest-sales order
lowest_order = df.loc[df["Total_Sales"].idxmin()]
print("Lowest-sales order:")
display(lowest_order.to_frame("Value"))

# Orders with sales between ₹5,000 and ₹10,000
mid_value_orders = df[df["Total_Sales"].between(5000, 10000)]
display(
    mid_value_orders[
        ["Order_ID", "City", "Category", "Product", "Total_Sales"]
    ].sort_values("Total_Sales", ascending=False)
)

Highest-sales order:

                                Value
Order_ID                         1049
Order_Date        2026-03-02 00:00:00
Customer                 Ishita Gupta
City                           Mumbai
Region                           West
Category                       Sports
Product                 Running Shoes
Quantity                            5
Unit_Price                       2799
Discount_Percent                    0
Total_Sales                   13995.0
Rating                            4.0
Payment_Method            Net Banking

Lowest-sales order:

                                Value
Order_ID                         1006
Order_Date        2026-01-21 00:00:00
Customer                    Manya Rao
City                            Kochi
Region                          South
Category                        Books
Product                 The Alchemist
Quantity                            1
Unit_Price                        499
Discount_Percent                   10
Total_Sales                     449.1
Rating                            4.2
Payment_Method       Cash on Delivery

    Order_ID         City        Category              Product  Total_Sales
69      1070        Delhi        Clothing               Jacket      9996.00
79      1080        Delhi        Clothing               Jacket      9996.00
51      1052   Chandigarh     Electronics  Mechanical Keyboard      9496.20
3       1004      Lucknow     Electronics  Mechanical Keyboard      9496.20
37      1038         Pune          Sports         Dumbbell Set      9495.25
95      1096        Kochi          Sports         Dumbbell Set      9495.25
9       1010        Kochi        Clothing               Jacket      8996.40
56      1057      Chennai  Home & Kitchen         Coffee Maker      8922.45
93      1094       Mumbai  Home & Kitchen        Mixer Grinder      8547.15
58      1059      Chennai          Sports          Cricket Bat      8496.60
92      1093    Hyderabad          Sports          Cricket Bat      8496.60
13      1014       Jaipur          Sports        Running Shoes      8397.00
32      1033         Pune  Home & Kitchen        Mixer Grinder      8097.30
61      1062       Mumbai     Electronics  Mechanical Keyboard      7497.00
16      1017    Hyderabad          Sports          Cricket Bat      7497.00
18      1019      Chennai        Clothing               Jacket      7497.00
10      1011    Hyderabad  Home & Kitchen         Coffee Maker      6998.00
40      1041        Delhi  Home & Kitchen         Coffee Maker      6648.10
50      1051  Bhubaneswar     Electronics          Smart Watch      6598.00
80      1081      Kolkata  Home & Kitchen      Electric Kettle      6370.75
7       1008        Jammu        Clothing               Hoodie      6076.20
97      1098    Bengaluru  Home & Kitchen      Electric Kettle      5996.00
75      1076      Chennai     Electronics  Wireless Headphones      5996.00
65      1066       Jaipur     Electronics          Smart Watch      5938.20
38      1039   Chandigarh  Home & Kitchen        Mixer Grinder      5698.10
27      1028   Chandigarh     Electronics  Wireless Headphones      5696.20
28      1029    Hyderabad     Electronics  Wireless Headphones      5696.20
76      1077         Pune  Home & Kitchen      Electric Kettle      5696.20
59      1060         Pune          Sports         Dumbbell Set      5397.30

## 12. Top-Performing Categories and Products

In [ ]:
print("Top 3 categories by total sales:")
display(category_summary.head(3))

print("Top 5 products by total sales:")
display(product_summary.head(5))

Top 3 categories by total sales:

                Total_Sales  Average_Sales  Total_Quantity  Number_of_Orders
Category
Sports            136026.45    5441.058000              79                25
Home & Kitchen    113329.90    5396.661905              59                21
Electronics        92086.00    4846.631579              57                19

Top 5 products by total sales:

                     Total_Sales  Total_Quantity  Number_of_Orders
Product
Coffee Maker            51610.25              16                 7
Jacket                  47106.15              20                 5
Cricket Bat             41483.40              18                 5
Running Shoes           41285.25              15                 5
Wireless Headphones     33877.40              23                 7

## 13. Meaningful Observations

In [ ]:
top_category = category_summary["Total_Sales"].idxmax()
top_city = city_summary["Total_Sales"].idxmax()
top_product = product_summary["Total_Sales"].idxmax()
top_payment = payment_summary["Total_Sales"].idxmax()
top_payment_avg = payment_summary["Average_Sales"].idxmax()

highest_order_id = df.loc[df["Total_Sales"].idxmax(), "Order_ID"]
lowest_order_id = df.loc[df["Total_Sales"].idxmin(), "Order_ID"]

print(f"1. Total sales were ₹{total_sales:,.2f}, with an average order value of ₹{average_sales:,.2f}.")
print(f"2. The highest-value order was {highest_order_id} at ₹{highest_sales:,.2f}.")
print(f"3. The lowest-value order was {lowest_order_id} at ₹{lowest_sales:,.2f}.")
print(f"4. {top_category} was the top category by total sales.")
print(f"5. {top_city} was the top city by total sales.")
print(f"6. {top_product} was the top product by total sales.")
print(f"7. {top_payment} generated the highest total sales among payment methods.")
print(f"8. {top_payment_avg} had the highest average order value.")
print(f"9. A total of {total_quantity} units were sold across {number_of_orders} orders.")
print("10. Sales value, order frequency, and quantity sold should all be considered when evaluating performance.")

1. Total sales were ₹447,262.95, with an average order value of ₹4,472.63.
2. The highest-value order was 1049 at ₹13,995.00.
3. The lowest-value order was 1006 at ₹449.10.
4. Sports was the top category by total sales.
5. Hyderabad was the top city by total sales.
6. Coffee Maker was the top product by total sales.
7. Credit Card generated the highest total sales among payment methods.
8. Net Banking had the highest average order value.
9. A total of 294 units were sold across 100 orders.
10. Sales value, order frequency, and quantity sold should all be considered when evaluating performance.

## 14. Conclusion

The analysis demonstrates how Pandas can be used to transform raw e-commerce transactions into useful business insights. Data selection, filtering, sorting, `groupby()`, and aggregation functions were used to compare performance across categories, cities, products, and payment methods.

These results can help identify strong-performing products and categories, high-value markets, and customer payment preferences.